### ISSUE TITLE
Review your own teams section in the ops-manual updates

### ISSUE THREAD

**Issue by Scarzy** [srobo/committee-tasks#14]
"di updates" branch

Note; it is not currently final, more changes are expected.

**Comment by Scarzy** [comment]
https://github.com/srobo/ops-manual/pull/35

**Comment by Scarzy** [comment]
Competition team: not looked
Marketing; unknown
Kit: Not looked
Volunteer onboarding: Yes
Fundraising: Kinda - trustees
Infrastructure: Yes

**Comment by PeterJCLaw** [comment]
@srobo/competition-committee @srobo/kit-committee @srobo/marketing-committee please ensure you have reviewed this before the next all committees meeting.
