### ISSUE TITLE
Flyers/business cards to aid fundraising

### ISSUE THREAD

**Issue by Scarzy** [srobo/committee-tasks#19]

**Comment by antoinepetty** [comment]
We have a design for business cards, just need printing if we haven't already
https://drive.google.com/file/d/1y4ssneOv8Qgo6AddMpiBhFbeKrRTxaFE/view?usp=sharing
https://drive.google.com/file/d/1PwfaDNnu4EdD7CQPyk4pITIWhfEkujTC/view?usp=sharing

**Comment by PeterJCLaw** [comment]
cc @srobo/marketing-committee for info.

**Comment by PeterJCLaw** [comment]
We have business cards! (They were shared at a recent Tech Day)
