### ISSUE TITLE
Consider suggestions on enforcement of Code of Conduct

### ISSUE THREAD

**Issue by Scarzy** [srobo/committee-tasks#2]
Look into how to make sure application of enforcement on discord is kept fair and arbitrary.

**Comment by Scarzy** [comment]
Some discussion has probably happened in Slack

**Comment by PeterJCLaw** [comment]
> Some discussion has probably happened in Slack

Here: https://studentrobotics.slack.com/archives/CBP7UL6RG/p1681734154844269?thread_ts=1681733922.056509&cid=CBP7UL6RG

**Comment by prophile** [comment]
Transferred over to comp team tasks list: https://github.com/srobo/tasks/issues/1234
