### ISSUE TITLE
Produce list of alternate storage options

### ISSUE THREAD

**Issue by Scarzy** [srobo/committee-tasks#20]

**Comment by PeterJCLaw** [comment]
@sedders123 & @RealOrangeOne ping on this?

**Comment by Scarzy** [comment]
Probably limited time to sort this before the competition.
Maybe beneficial to move some stuff over competition weekend, but only if there's time to sort things beforehand and on the day

**Comment by PeterJCLaw** [comment]
Availability has appeared at the one near Diane. It's not especially big. ~35 square foot floor space, at least 2m tall.
It's a barn which has been converted. Unclear how weather proof it is. Inaccessible from public transport, though closer to our volunteers.
Main concern is the size -- we don't think that 35 sq. ft. is enough.

The other options previously considered are in Horsham itself, which is more convenient, but more expensive.

Options a bit further afield, e.g: closer to Gatwick, may also be worth considering if cheaper given that storage/commercial properties are more common there.

Current storage is half a standard shipping container -- 10ft × 8ft × 8ft. Fairly well weatherproofed.

**Comment by Scarzy** [comment]
Di is due to jump on a 50sq. ft. container in Horsham as/when one pops up. Kit team continuing to look in the mean time
