### ISSUE TITLE
Run an assumptions survey

### ISSUE THREAD

**Issue by Scarzy** [srobo/committee-tasks#3]
We should gather questions which we want to learn about teams, send it out and then analyse the results.

**Comment by Scarzy** [comment]
Document was sent out. The survey has not gone out.
Jake to send it out

**Comment by Scarzy** [comment]
Teams to be nudged to confirm they are happy with it

**Comment by RealOrangeOne** [comment]
Assumptions questions: https://docs.google.com/document/d/1oevylWortiEEizlMfb5sTMMMWkFKkttcRWE6XuYv7BA/edit?usp=sharing

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/tasks/issues/304 might be something to include in this.

**Comment by PeterJCLaw** [comment]
@RealOrangeOne ping on this?

**Comment by Scarzy** [comment]
Jake to review suggestions and send imminently

**Comment by PeterJCLaw** [comment]
Aim to send this to team supervisors who:
- attended SR2022
- signed up for SR2023, SR2024
